site_name: PyDocs
pages:
- Home: index.md
- Python基础:
  - 关于Python: Tutorial/about-python.md
  - 安装Python: Tutorial/install.md
- Python的库:
  - 关于库: Library/about-library.md
- Django:
  - 关于Django: Django/about-django.md
- Intermediate:
  - Python进阶: Intermediate/about-intermediate.md
- About: about.md
copyright: ©2016 pydocs.cn
site_url: http://pydocs.cn
repo_url: https://github.com/pierre94/PyDocs
site_description: 高效、快乐、简单的Python文库
site_favicon: http://7rf2gl.com1.z0.glb.clouddn.com/favicon.png
